### ISSUE TITLE
Auth issue

### ISSUE THREAD

**Issue by nevaus** [sergioperez/fronius-auth-proxy#1]
hi Sergio,
Thanks for making this utility. I have managed to get Podman going, and I feel I have made it quite far (for someone that has very little experience with containers), but I seem to be getting an authentication error when testing with Curl. I am fully certain I am using the correct credentials for the Fronius inverter service account (I am able to log in to the inverter via the usual Web UI using these creds). Any ideas what I am doing wrong? See output below..
(P/w consists of letters and numbers, in case that matters)
(I am using Fronius Primo 5.0-1 with firmware 3.26.1-3)
Cheers.

```

Requested Route: /request
{
  powerLimits: {
    exportLimits: { activePower: [Object], failSafeModeEnabled: false },
    visualization: { exportLimits: [Object], wattPeakReferenceValue: 10000 }
  }
}
POST
AUTH FOUND
[
  'Digest username="service"',
  ' realm="Webinterface area"',
  ' nonce="<hidden>:<hidden>"',
  ' uri="/config/exportlimit/?method=save"',
  ' response="<hidden>"',
  ' qop=auth',
  ' nc=00000005',
  ' cnonce="<hidden>"'
]
Digest username="service", realm="Webinterface area", nonce="<hidden>:<hidden>", uri="/config/exportlimit/?method=save", response="<hidden>", qop=auth, nc=00000005, cnonce="<hidden>"
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
         "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
 <head>
  <title>401 Unauthorized</title>
 </head>
 <body>
  <h1>401 Unauthorized</h1>
 </body>
</html>
```

**Comment by nevaus** [comment]
I have sorted out the issue. Your example has a '%' sign at the end of "SERVICE_USER_PASSWORD". Once I removed that, it seemed to work, cheers :)

**Comment by youbet1980** [comment]
How did you get podman to run on home assistant. I get
bash: podman: command not found.

![Screen Shot 2024-02-13 at 10 47 11 am](https://github.com/sergioperez/fronius-auth-proxy/assets/48540186/f62a18ee-a867-4e56-bfad-0c9bcaea1c77)

**Comment by youbet1980** [comment]
How did you get the podman to work on home assistant I get podman not found.
![Screen Shot 2024-02-13 at 10 46 37 am](https://github.com/sergioperez/fronius-auth-proxy/assets/48540186/36633d54-d31f-4981-b36c-ab97160c08e4)
